### ISSUE TITLE
Update information about support in Firefox

### ISSUE THREAD

**Issue by opl-** [helmetjs/dont-sniff-mimetype#2]
The [Bugzilla bug](https://bugzilla.mozilla.org/show_bug.cgi?id=471020) referenced in the readme has been marked as fixed since November of 2016 and support for the header has been live since Firefox 50.

The readme file should be updated to reflect that change.

**Comment by EvanHahn** [comment]
Thanks for reporting this!

Would you like to open a pull request?

**Comment by opl-** [comment]
Why not. See #3
